# Generated by Django 5.2.4 on 2025-07-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='チェックイン日')),
                ('check_out_date', models.DateField(verbose_name='チェックアウト日')),
                ('check_in_time', models.CharField(max_length=10, verbose_name='チェックイン時間')),
                ('lodging', models.CharField(max_length=100, verbose_name='宿')),
                ('adult_male', models.IntegerField(default=0, verbose_name='大人（男性）')),
                ('adult_female', models.IntegerField(default=0, verbose_name='大人（女性）')),
                ('child_7_12', models.IntegerField(default=0, verbose_name='7～12歳')),
                ('child_under_6', models.IntegerField(default=0, verbose_name='6歳以下')),
                ('last_name', models.CharField(max_length=50, verbose_name='申込者名 (姓)')),
                ('first_name', models.CharField(max_length=50, verbose_name='申込者名 (名)')),
                ('last_name_kana', models.CharField(max_length=50, verbose_name='フリガナ (セイ)')),
                ('first_name_kana', models.CharField(max_length=50, verbose_name='フリガナ (メイ)')),
                ('gender', models.CharField(max_length=20, verbose_name='性別')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('postal_code_1', models.CharField(max_length=3, verbose_name='郵便番号1')),
                ('postal_code_2', models.CharField(max_length=4, verbose_name='郵便番号2')),
                ('prefecture', models.CharField(max_length=10, verbose_name='都道府県')),
                ('city', models.CharField(max_length=50, verbose_name='市区町村')),
                ('street', models.TextField(blank=True, null=True, verbose_name='番地・建物名')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='予約作成日時')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'ordering': ['-created_at'],
            },
        ),
    ]
