# docker-compose.yml (nouhaku-websiteのルートディレクトリに配置)

services:
  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=farmstay_db
      - POSTGRES_USER=farmstay_user
      - POSTGRES_PASSWORD=T4keastr0ll
    ports:
      - "5433:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
      - ./backend/.env.local
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # ★修正: build args を削除
      # args:
      #   NEXT_PUBLIC_API_URL: http://backend:8000 
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    # environmentセクションも削除（もしあれば）
    # environment:
    #   NEXT_PUBLIC_API_URL: http://backend:8000 
volumes:
  pg_data:
  media_data:
