# docker-compose.yml
version: '3.8' # ★この行のスペルとインデントを再確認

services:
  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=farmstay_db
      - POSTGRES_USER=farmstay_user
      - POSTGRES_PASSWORD=T4keastr0ll
    ports:
      - "5433:5432"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env # このファイルが存在することを確認！
      - ./backend/.env.local # このファイルは存在しているはず
    # environment: # この行と、これ以降のenvironmentに関するコメントは全て削除する
    depends_on:
      - db

volumes:
  pg_data:
  media_data: