# docker-compose.yml (nouhaku-websiteのルートディレクトリに配置)

version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/
    # env_file: は削除されたまま
    environment: # ここに環境変数を直接記述します
      - POSTGRES_DB=farmstay_db
      - POSTGRES_USER=farmstay_user
      - POSTGRES_PASSWORD=T4keastr0ll
    ports:
      - "5432:5432"

  backend:
    build:
      context: . # ★プロジェクトのルートディレクトリをビルドコンテキストとする
      dockerfile: backend/Dockerfile # ★backendフォルダ内のDockerfileを指定
    command: python manage.py runserver 0.0.0.0:8000 # manage.pyはルートにある
    volumes:
      - .:/app # ★プロジェクトルート全体をコンテナの/appにマウント
      - media_data:/app/media
    ports:
      - "8000:8000"
    # env_file: は削除されたまま
    environment: # ここに環境変数を直接記述します
      - DJANGO_SECRET_KEY=your_secret_key_here
      - POSTGRES_DB=farmstay_db
      - POSTGRES_USER=farmstay_user
      - POSTGRES_PASSWORD=T4keastr0ll
    depends_on:
      - db

  # frontend: # frontendサービスはこのdocker-compose.ymlから削除済みです
  # （ローカルで直接 npm run dev するため）

volumes:
  pg_data:
  media_data: