# Generated by Django 5.2.3 on 2025-06-13 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('message', models.TextField(verbose_name='問い合わせ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('status', models.CharField(choices=[('Pending', '処理待ち'), ('Processed', '処理済み')], default='Pending', max_length=10, verbose_name='ステータス')),
            ],
            options={
                'verbose_name': '問い合わせ',
                'verbose_name_plural': '問い合わせ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='町名')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(verbose_name='説明')),
                ('image', models.ImageField(blank=True, null=True, upload_to='town_images/', verbose_name='画像')),
            ],
            options={
                'verbose_name': '町',
                'verbose_name_plural': '町',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='施設名')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(verbose_name='説明')),
                ('location', models.CharField(max_length=255, verbose_name='所在地')),
                ('capacity', models.IntegerField(verbose_name='収容人数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='house_images/', verbose_name='画像')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='core.town', verbose_name='関連する町')),
            ],
            options={
                'verbose_name': '家',
                'verbose_name_plural': '家',
                'ordering': ['name'],
            },
        ),
    ]
