# Generated by Django 5.2.3 on 2025-07-04 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(max_length=255, verbose_name='メイン見出し')),
                ('sub_heading', models.CharField(blank=True, max_length=255, null=True, verbose_name='サブ見出し')),
                ('introduction_text', models.TextField(verbose_name='紹介文')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='homepage/', verbose_name='ヒーロー画像')),
                ('stay_link_text', models.CharField(default='滞在について', max_length=100, verbose_name='滞在リンクテキスト')),
                ('eat_link_text', models.CharField(default='食事について', max_length=100, verbose_name='食事リンクテキスト')),
                ('explore_link_text', models.CharField(default='体験について', max_length=100, verbose_name='体験リンクテキスト')),
            ],
            options={
                'verbose_name': 'トップページコンテンツ',
                'verbose_name_plural': 'トップページコンテンツ',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='アクティビティ名・スポット名')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(verbose_name='詳細説明')),
                ('location_detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='場所の詳細')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='関連リンク')),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/', verbose_name='画像')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.town', verbose_name='関連する町')),
            ],
            options={
                'verbose_name': '体験・観光',
                'verbose_name_plural': '体験・観光',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='体験・料理名')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='スラッグ')),
                ('description', models.TextField(verbose_name='詳細説明')),
                ('price_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='価格帯')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_experiences/', verbose_name='画像')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_experiences', to='core.town', verbose_name='関連する町')),
            ],
            options={
                'verbose_name': '食体験',
                'verbose_name_plural': '食体験',
                'ordering': ['name'],
            },
        ),
    ]
